# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: vs2017-win2016

steps:
- task: CredScan@2
  displayName: Run CredScan
  inputs:
    toolMajorVersion: V2
    verboseOutput: true
    debugMode: false
    folderSuppression: false
- task: PostAnalysis@1
  displayName: Post Analysis
  inputs:
    CredScan: true