apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: javaee-cafe-cluster-agic
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: ${param.sc.service.account.name}
  replicas: 3
  applicationImage: ${param.login.server}/javaee-cafe:v1
  pullPolicy: Always
  service:
    type: ClusterIP
    targetPort: 9080
  envFrom:
  - secretRef:
      name: ${param.sc.secret.name}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: javaee-cafe-cluster-agic-ingress
  annotations:
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/use-private-ip: "false"
spec:
  ingressClassName: azure-application-gateway
  tls:
  - secretName: ${param.ingress.tls.secret}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: javaee-cafe-cluster-agic
            port:
              number: 9080
