apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: javaee-cafe-cluster-agic
spec:
  replicas: 3
  applicationImage: ${param.login.server}/javaee-cafe:${project.version}
  pullPolicy: Always
  service:
    type: ClusterIP
    targetPort: 9080
  env:
  - name: DB_SERVER_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-sql
        key: db.server.name
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-sql
        key: db.name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db-secret-sql
        key: db.user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret-sql
        key: db.password
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: javaee-cafe-cluster-agic-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/use-private-ip: "false"
spec:
  tls:
  - secretName: ${param.ingress.tls.secret}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: javaee-cafe-cluster-agic
            port:
              number: 9080
