apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: javaee-cafe-cluster
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: ${param.sc.service.account.name}
  replicas: 3
  applicationImage: ${param.login.server}/javaee-cafe:v1
  pullPolicy: Always
  service:
    type: LoadBalancer
    targetPort: 9080
    port: 80
  envFrom:
  - secretRef:
      name: ${param.sc.secret.name}
