apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: javaee-cafe-cluster
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server
    metric: Processor Value Unit (PVU)
    productEntitlementSource: Standalone
  replicas: 3
  applicationImage: ${param.login.server}/javaee-cafe:v1
  pullPolicy: Always
  manageTLS: false
  service:
    type: LoadBalancer
    targetPort: 9080
    port: 80
  env:
  - name: DB_SERVER_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-sql
        key: db.server.name
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-sql
        key: db.name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db-secret-sql
        key: db.user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret-sql
        key: db.password
