# DisableDockerDetector "liberty-maven-plugin does not support docker buildx-build. See https://github.com/OpenLiberty/ci.maven/issues/1589"
# WebSphere Liberty base image
FROM icr.io/appcafe/websphere-liberty:kernel-java17-openj9-ubi

# Add config files
COPY --chown=1001:0 liberty/wlp/usr/servers/defaultServer/server.xml /config/server.xml
COPY --chown=1001:0 liberty/wlp/usr/servers/defaultServer/bootstrap.properties /config/bootstrap.properties

# This script will add the requested XML snippets to enable Liberty features and grow image to be fit-for-purpose using featureUtility.
# Only available in 'kernel-slim'. The 'full' tag already includes all features for convenience.
RUN features.sh

# Add app and other dependencies
COPY --chown=1001:0 ${project.artifactId}.war /config/apps/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/byte-buddy-1.14.5.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/cache-api-1.1.1.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/jackson-annotations-2.15.2.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/jackson-core-2.15.2.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/jackson-databind-2.15.2.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/jackson-dataformat-yaml-2.15.2.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/jboss-marshalling-2.0.11.Final.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/jboss-marshalling-river-2.0.11.Final.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/jodd-bean-5.1.6.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/jodd-core-5.1.6.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/kryo-5.5.0.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/minlog-1.3.1.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/netty-buffer-4.1.96.Final.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/netty-codec-4.1.96.Final.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/netty-codec-dns-4.1.96.Final.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/netty-common-4.1.96.Final.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/netty-handler-4.1.96.Final.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/netty-resolver-4.1.96.Final.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/netty-resolver-dns-4.1.96.Final.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/netty-transport-4.1.96.Final.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/netty-transport-native-unix-common-4.1.96.Final.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/objenesis-3.3.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/reactive-streams-1.0.4.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/reactor-core-3.5.3.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/redisson-3.23.4.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/reflectasm-1.11.9.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/rxjava-3.1.6.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/slf4j-api-1.7.36.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/slf4j-simple-1.7.36.jar /opt/ibm/wlp/usr/shared/resources/
COPY --chown=1001:0 ${project.artifactId}/WEB-INF/lib/snakeyaml-2.0.jar /opt/ibm/wlp/usr/shared/resources/

# This script will add the requested XML snippets, grow image to be fit-for-purpose and apply interim fixes
RUN configure.sh
