# DisableDockerDetector "liberty-maven-plugin does not support docker buildx-build. See https://github.com/OpenLiberty/ci.maven/issues/1589"
# WebSphere Liberty base image
FROM icr.io/appcafe/websphere-liberty:kernel-java17-openj9-ubi

# Add config files
COPY --chown=1001:0 src/main/liberty/config/server.xml /config/server.xml

# This script will add the requested XML snippets to enable Liberty features and grow image to be fit-for-purpose using featureUtility.
# Only available in 'kernel-slim'. The 'full' tag already includes all features for convenience.
RUN features.sh

# Add app and other dependencies
COPY --chown=1001:0 target/javaee-cafe-jcache.war /config/apps/
COPY --chown=1001:0 target/liberty/wlp/usr/shared/resources /opt/ibm/wlp/usr/shared/resources

# This script will add the requested XML snippets, grow image to be fit-for-purpose and apply interim fixes
RUN configure.sh
