apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: ${project.artifactId}-cluster
spec:
  replicas: ${param.replicas}
  applicationImage: ${param.login.server}/${project.artifactId}:${project.version}
  pullPolicy: Always
  service:
    type: LoadBalancer
    targetPort: 9080
    port: 80
