name: AKS: Update Cafe App with PostgreSQL DB connection

on:
  workflow_dispatch:
    inputs:
      acrName: 
        description: "ACR name"
        required: true
        default: 'acr290e62'
      appDeploymentYamlEncoded:
        description: "Encoded deployment file"
        required: true
        default: 'IyAgICAgIENvcHlyaWdodCAoYykgTWljcm9zb2Z0IENvcnBvcmF0aW9uLgojIAojICBMaWNlbnNlZCB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wICh0aGUgIkxpY2Vuc2UiKTsKIyAgeW91IG1heSBub3QgdXNlIHRoaXMgZmlsZSBleGNlcHQgaW4gY29tcGxpYW5jZSB3aXRoIHRoZSBMaWNlbnNlLgojICBZb3UgbWF5IG9idGFpbiBhIGNvcHkgb2YgdGhlIExpY2Vuc2UgYXQKIyAKIyAgICAgICAgICAgaHR0cDovL3d3dy5hcGFjaGUub3JnL2xpY2Vuc2VzL0xJQ0VOU0UtMi4wCiMgCiMgIFVubGVzcyByZXF1aXJlZCBieSBhcHBsaWNhYmxlIGxhdyBvciBhZ3JlZWQgdG8gaW4gd3JpdGluZywgc29mdHdhcmUKIyAgZGlzdHJpYnV0ZWQgdW5kZXIgdGhlIExpY2Vuc2UgaXMgZGlzdHJpYnV0ZWQgb24gYW4gIkFTIElTIiBCQVNJUywKIyAgV0lUSE9VVCBXQVJSQU5USUVTIE9SIENPTkRJVElPTlMgT0YgQU5ZIEtJTkQsIGVpdGhlciBleHByZXNzIG9yIGltcGxpZWQuCiMgIFNlZSB0aGUgTGljZW5zZSBmb3IgdGhlIHNwZWNpZmljIGxhbmd1YWdlIGdvdmVybmluZyBwZXJtaXNzaW9ucyBhbmQKIyAgbGltaXRhdGlvbnMgdW5kZXIgdGhlIExpY2Vuc2UuCgphcGlWZXJzaW9uOiBvcGVubGliZXJ0eS5pby92MWJldGExCmtpbmQ6IE9wZW5MaWJlcnR5QXBwbGljYXRpb24KbWV0YWRhdGE6CiAgbmFtZTogYXBwMjkwZTYyCiAgbmFtZXNwYWNlOiBwcm9qZWN0MjkwZTYyCnNwZWM6CiAgcmVwbGljYXM6IDIKICBhcHBsaWNhdGlvbkltYWdlOiBhY3IyOTBlNjIuYXp1cmVjci5pby9pbWFnZTI5MGU2MjoxLjAuMAogIHB1bGxTZWNyZXQ6IGFwcDI5MGU2Mi1zZWNyZXQKICBzZXJ2aWNlOgogICAgdHlwZTogTG9hZEJhbGFuY2VyCiAgICBwb3J0OiA5MDgwCg=='
      appDockerfileEncoded:
        description: "Encoded Dockerfile"
        required: true
        default: 'IyAgICAgIENvcHlyaWdodCAoYykgTWljcm9zb2Z0IENvcnBvcmF0aW9uLgojIAojICBMaWNlbnNlZCB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wICh0aGUgIkxpY2Vuc2UiKTsKIyAgeW91IG1heSBub3QgdXNlIHRoaXMgZmlsZSBleGNlcHQgaW4gY29tcGxpYW5jZSB3aXRoIHRoZSBMaWNlbnNlLgojICBZb3UgbWF5IG9idGFpbiBhIGNvcHkgb2YgdGhlIExpY2Vuc2UgYXQKIyAKIyAgICAgICAgICAgaHR0cDovL3d3dy5hcGFjaGUub3JnL2xpY2Vuc2VzL0xJQ0VOU0UtMi4wCiMgCiMgIFVubGVzcyByZXF1aXJlZCBieSBhcHBsaWNhYmxlIGxhdyBvciBhZ3JlZWQgdG8gaW4gd3JpdGluZywgc29mdHdhcmUKIyAgZGlzdHJpYnV0ZWQgdW5kZXIgdGhlIExpY2Vuc2UgaXMgZGlzdHJpYnV0ZWQgb24gYW4gIkFTIElTIiBCQVNJUywKIyAgV0lUSE9VVCBXQVJSQU5USUVTIE9SIENPTkRJVElPTlMgT0YgQU5ZIEtJTkQsIGVpdGhlciBleHByZXNzIG9yIGltcGxpZWQuCiMgIFNlZSB0aGUgTGljZW5zZSBmb3IgdGhlIHNwZWNpZmljIGxhbmd1YWdlIGdvdmVybmluZyBwZXJtaXNzaW9ucyBhbmQKIyAgbGltaXRhdGlvbnMgdW5kZXIgdGhlIExpY2Vuc2UuCgojIE9wZW4gTGliZXJ0eSBiYXNlIGltYWdlCkZST00gb3BlbmxpYmVydHkvb3Blbi1saWJlcnR5Omtlcm5lbC1qYXZhOC1vcGVuajktdWJpCgojIEFkZCBjb25maWcgYW5kIGFwcApDT1BZIC0tY2hvd249MTAwMTowIHNlcnZlci54bWwgL2NvbmZpZy9zZXJ2ZXIueG1sCkNPUFkgLS1jaG93bj0xMDAxOjAgYXBwMjkwZTYyLndhciAvY29uZmlnL2FwcHMvCgojIFRoaXMgc2NyaXB0IHdpbGwgYWRkIHRoZSByZXF1ZXN0ZWQgWE1MIHNuaXBwZXRzLCBncm93IGltYWdlIHRvIGJlIGZpdC1mb3ItcHVycG9zZSBhbmQgYXBwbHkgaW50ZXJpbSBmaXhlcwpSVU4gY29uZmlndXJlLnNoCg=='
      appImage:
        description: "App image"
        required: true
        default: 'image290e62:1.0.0'
      appName:
        description: "Open Liberty App name"
        required: true
        default: 'app290e62'
      appNamespace:
        description: "Open Liberty App namespace"
        required: true
        default: 'project290e62'
      appServerXmlEncoded:
        description: "Encoded Server.xml"
        required: true
        default: 'PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCEtLQogICAgIENvcHlyaWdodCAoYykgTWljcm9zb2Z0IENvcnBvcmF0aW9uLgoKIExpY2Vuc2VkIHVuZGVyIHRoZSBBcGFjaGUgTGljZW5zZSwgVmVyc2lvbiAyLjAgKHRoZSAiTGljZW5zZSIpOwogeW91IG1heSBub3QgdXNlIHRoaXMgZmlsZSBleGNlcHQgaW4gY29tcGxpYW5jZSB3aXRoIHRoZSBMaWNlbnNlLgogWW91IG1heSBvYnRhaW4gYSBjb3B5IG9mIHRoZSBMaWNlbnNlIGF0CgogICAgICAgICAgaHR0cDovL3d3dy5hcGFjaGUub3JnL2xpY2Vuc2VzL0xJQ0VOU0UtMi4wCgogVW5sZXNzIHJlcXVpcmVkIGJ5IGFwcGxpY2FibGUgbGF3IG9yIGFncmVlZCB0byBpbiB3cml0aW5nLCBzb2Z0d2FyZQogZGlzdHJpYnV0ZWQgdW5kZXIgdGhlIExpY2Vuc2UgaXMgZGlzdHJpYnV0ZWQgb24gYW4gIkFTIElTIiBCQVNJUywKIFdJVEhPVVQgV0FSUkFOVElFUyBPUiBDT05ESVRJT05TIE9GIEFOWSBLSU5ELCBlaXRoZXIgZXhwcmVzcyBvciBpbXBsaWVkLgogU2VlIHRoZSBMaWNlbnNlIGZvciB0aGUgc3BlY2lmaWMgbGFuZ3VhZ2UgZ292ZXJuaW5nIHBlcm1pc3Npb25zIGFuZAogbGltaXRhdGlvbnMgdW5kZXIgdGhlIExpY2Vuc2UuCi0tPgoKPHNlcnZlciBkZXNjcmlwdGlvbj0iZGVmYXVsdFNlcnZlciI+CiAgICA8IS0tIFRPRE86IEVuYWJsZSBmZWF0dXJlcyB0aGF0J3JlIHNwZWNpZmllZCBieSB1c2VyIC0tPgogICAgPGZlYXR1cmVNYW5hZ2VyPgogICAgICAgIDxmZWF0dXJlPmphdmFlZS04LjA8L2ZlYXR1cmU+CiAgICAgICAgPGZlYXR1cmU+bWljcm9Qcm9maWxlLTMuMzwvZmVhdHVyZT4KICAgIDwvZmVhdHVyZU1hbmFnZXI+CgogICAgPCEtLSBUT0RPOiBEZWZpbmUgaHR0cCAmIGh0dHBzIGVuZHBvaW50cyB3aXRoIHVzZXIgc3BlY2lmaWVkIHBvcnRzIC0tPgogICAgPGh0dHBFbmRwb2ludCBpZD0iZGVmYXVsdEh0dHBFbmRwb2ludCIgaG9zdD0iKiIKICAgICAgICBodHRwUG9ydD0iOTA4MCIgaHR0cHNQb3J0PSI5NDQzIiAvPgoKICAgIDwhLS0gQXV0b21hdGljYWxseSBleHBhbmQgV0FSIGZpbGVzIGFuZCBFQVIgZmlsZXMgLS0+CiAgICA8YXBwbGljYXRpb25NYW5hZ2VyIGF1dG9FeHBhbmQ9InRydWUiIC8+CgogICAgPCEtLSBEZWZpbmUgd2ViIGFwcGxpY2F0aW9uIHdpdGggaXRzIGNvbnRleHQgcm9vdCBhbmQgbG9jYXRpb24gLS0+CiAgICA8d2ViQXBwbGljYXRpb24gaWQ9ImFwcDI5MGU2MiIgY29udGV4dFJvb3Q9Ii9qYXZhZWVjYWZlIgogICAgICAgIGxvY2F0aW9uPSIke3NlcnZlci5jb25maWcuZGlyfS9hcHBzL2FwcDI5MGU2Mi53YXIiPgogICAgPC93ZWJBcHBsaWNhdGlvbj4KPC9zZXJ2ZXI+Cg=='
      clusterName: 
        description: "AKS cluster name"
        required: true
        default: 'cluster290e62'
      clusterRGName: 
        description: "AKS cluster resource group name"
        required: true
        default: 'zhengtest0928rg'
  repository_dispatch:

env:
    acrPassword: ${{ secrets.ACR_PASSWORD }}
    # description: "ACR password"
    # required: true
    # default: 'Vnhbk2f0nGX=LubJJVZTafm9aeuB=Xik'
    azCliVersion: 2.23.0
    azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
    dbAdminUser: ${{ secrets.DB_ADMIN_USER }}
    # description: 'DB username'
    # required: true
    # default: 'zchang@zhengtestdb0928'
    dbPassword: ${{ secrets.DB_PASSWORD }}
    # description: 'DB password'
    # required: true
    # default: 'Secret123!'
    dbServerName: ${{ secrets.DB_SERVER_NAME }}
    # description: 'Server name of the database'
    # required: true
    # default: 'zhengtestdb0928'
    location: eastus

jobs:
    deploy-app:
        runs-on: ubuntu-latest
        steps:
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: Install xmlstarlet
              run: |
                sudo apt-get install -y xmlstarlet
            - name: Install Docker
              run: |
                # Install docker
                sudo apt-get -q update
                sudo apt-get -y -q install apt-transport-https
                curl -m 120 -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
                echo \
                    "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
                sudo apt-get -q update
                sudo apt-get -y -q install docker-ce docker-ce-cli containerd.io

                echo "docker version"
                sudo docker --version
                sudo systemctl start docker
            - uses: azure/login@v1
              id: azure-login
              with:
                creds: ${{ env.azureCredentials }}
            - name: Checkout open-liberty-on-aks
              uses: actions/checkout@v2
            - name: Build the app
              run: |
                echo "build the Cafe web app"
                cd 3-integration/connect-db/postgres
                mvn clean install -Ddb.server.name=${{ env.dbServerName }}.postgres.database.azure.com -Ddb.port.number=5432 -Ddb.name=postgres -Ddb.user=${{ env.dbAdminUser }} -Ddb.password=${{ env.dbPassword }}
            - name: Download PostgreSQL driver
              run: |
                cd 3-integration/connect-db/postgres
                wget -O postgresql-42.2.4.jar https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.4/postgresql-42.2.4.jar
            - name: Generate Server.xml
              run: |
                cd 3-integration/connect-db/postgres
                echo ${{ github.event.inputs.appServerXmlEncoded }} | base64 --decode >> server.xml
                xmlstarlet edit --inplace \
                    -d '/server/featureManager/feature' \
                    -d '/server/featureManager/feature[2]' \
                    -s '//featureManager' -t elem -n "feature" -v "cdi-2.0" \
                    -s '//featureManager' -t elem -n "feature" -v "jaxb-2.2" \
                    -s '//featureManager' -t elem -n "feature" -v "jsf-2.3" \
                    -s '//featureManager' -t elem -n "feature" -v "jaxrs-2.1" \
                    -s '//featureManager' -t elem -n "feature" -v "ejbLite-3.2" \
                    -s '//featureManager' -t elem -n "feature" -v "jpa-2.2" \
                    -s '//server' -t elem -n "dataSource" \
                    -s '//dataSource' -t attr -n "id" -v "JavaEECafeDB" \
                    -s '//dataSource' -t attr -n "jndiName" -v "jdbc/JavaEECafeDB" \
                    -s '//server/dataSource[last()]' -t elem -n "jdbcDriver" \
                    -s '//jdbcDriver' -t attr -n "libraryRef" -v "driver-library" \
                    -s '//server/dataSource[last()]' -t elem -n "properties.postgresql" \
                    -s '//properties.postgresql' -t attr -n "serverName" -v "\${db.server.name}" \
                    -s '//properties.postgresql' -t attr -n "portNumber" -v "\${db.port.number}" \
                    -s '//properties.postgresql' -t attr -n "databaseName" -v "\${db.name}" \
                    -s '//properties.postgresql' -t attr -n "user" -v "\${db.user}" \
                    -s '//properties.postgresql' -t attr -n "password" -v "\${db.password}" \
                    -s '//properties.postgresql' -t attr -n "ssl" -v "\${db.ssl}" \
                    -s '//server' -t elem -n "variable" \
                    -s '//variable' -t attr -n "name" -v "db.ssl" \
                    -s '//variable' -t attr -n "defaultValue" -v "true" \
                    -s '//server' -t elem -n "library" \
                    -s '//library' -t attr -n "id" -v "driver-library" \
                    -s '//server/library[last()]' -t elem -n "fileset" \
                    -s '//fileset' -t attr -n "dir" -v "\${shared.resource.dir}" \
                    -s '//fileset' -t attr -n "includes" -v "*.jar" \
                    -u '/server/webApplication/@location' -v "\${server.config.dir}/apps/javaee-cafe.war" \
                    server.xml
            - name: Archive server.xml
              uses: actions/upload-artifact@v1
              with:
                name: archivefiles
                path: 3-integration/connect-db/postgres/server.xml
            - name: Generate deployment file
              run: |
                cd 3-integration/connect-db/postgres
                echo ${{ github.event.inputs.appDeploymentYamlEncoded }} | base64 --decode >> openlibertyapplication.yaml
                cat <<EOT >> openlibertyapplication.yaml
                  env:
                  - name: DB_SERVER_NAME
                    valueFrom:
                      secretKeyRef:
                        name: db-secret-postgres
                        key: db.server.name
                  - name: DB_PORT_NUMBER
                    valueFrom:
                      secretKeyRef:
                        name: db-secret-postgres
                        key: db.port.number
                  - name: DB_NAME
                    valueFrom:
                      secretKeyRef:
                        name: db-secret-postgres
                        key: db.name
                  - name: DB_USER
                    valueFrom:
                      secretKeyRef:
                        name: db-secret-postgres
                        key: db.user
                  - name: DB_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: db-secret-postgres
                        key: db.password
                EOT
            - name: Generate Dockerfile
              run: |
                cd 3-integration/connect-db/postgres
                echo ${{ github.event.inputs.appDockerfileEncoded }} | base64 --decode >> Dockerfile
                # Remove current app configuration
                sed -i "/${{ github.event.inputs.appName }}/d" Dockerfile
                lineNumber=$(grep -n 'COPY' Dockerfile | grep -Eo '^[^:]+')
                # Add postgresql driver
                sed -i "$lineNumber a COPY --chown=1001:0 postgresql-42.2.4.jar \/opt\/ol\/wlp\/usr\/shared\/resources\/" Dockerfile
                # Add built Cafe web app
                sed -i "$lineNumber a COPY --chown=1001:0 target/javaee-cafe.war \/config\/apps\/" Dockerfile
            - name: Archive Dockerfile
              uses: actions/upload-artifact@v1
              with:
                name: archivefiles
                path: 3-integration/connect-db/postgres/Dockerfile
            - name: Build image
              run: |
                cd 3-integration/connect-db/postgres
                docker build -t javaee-cafe-connect-db-postgres:1.0.0 --pull --file=Dockerfile .
            - name: Push image
              run: |
                Container_Registry_URL=${{ github.event.inputs.acrName }}.azurecr.io
                IFS=':' read -a arr <<< ${{ github.event.inputs.appImage }}
                Image_Name=${arr[0]}
                echo $Image_name
                docker tag javaee-cafe-connect-db-postgres:1.0.0 ${Container_Registry_URL}/${Image_Name}:${{ github.run_id }}${{ github.run_number }}
                docker login -u ${{ github.event.inputs.acrName }} -p ${{ env.acrPassword }} ${Container_Registry_URL}
                docker push ${Container_Registry_URL}/${Image_Name}:${{ github.run_id }}${{ github.run_number }}
            - name: Create DB Secret file
              run: |
                cd 3-integration/connect-db/postgres
                export NAMESPACE=${{ github.event.inputs.appNamespace }}
                export DB_SERVER_NAME=${{ env.dbServerName }}.postgres.database.azure.com
                export DB_PORT_NUMBER=5432
                export DB_NAME=postgres
                export DB_USER=${{ env.dbAdminUser }}
                export DB_PASSWORD=${{ env.dbPassword }}

                envsubst < db-secret.yaml > db-secret-sub.yaml
            - name: Archive db-secret-sub.yaml
              uses: actions/upload-artifact@v1
              with:
                name: archivefiles
                path: 3-integration/connect-db/postgres/db-secret-sub.yaml
            - name: Update image path and place in values
              run: |
                cd 3-integration/connect-db/postgres
                Container_Registry_URL=${{ github.event.inputs.acrName }}.azurecr.io
                IFS=':' read -a arr <<< ${{ github.event.inputs.appImage }}
                Image_Name=${arr[0]}
                sed -i "/applicationImage/d" openlibertyapplication.yaml
                lineNumber=$(grep -n 'replicas' openlibertyapplication.yaml | grep -Eo '^[^:]+')
                sed -i "$lineNumber a \  applicationImage: ${Container_Registry_URL}/${Image_Name}:${{ github.run_id }}${{ github.run_number }}" openlibertyapplication.yaml
            - name: Archive openlibertyapplication.yaml
              uses: actions/upload-artifact@v1
              with:
                name: archivefiles
                path: 3-integration/connect-db/postgres/openlibertyapplication.yaml
            - name: Connect to AKS cluster
              run: |
                cd 3-integration/connect-db/postgres
                az aks get-credentials --resource-group ${{ github.event.inputs.clusterRGName }} --name ${{ github.event.inputs.clusterName }}
                cat db-secret-sub.yaml
                kubectl apply -f db-secret-sub.yaml
                cat openlibertyapplication.yaml
                kubectl apply -f openlibertyapplication.yaml
